#!/usr/bin/env python3
"""
generate_seed_from_api.py

Convert raw Battle.net JSON data (from fetch_blizzard_data.py) into Lua
seed files for CombatAnalytics.

Usage:
    python scripts/generate_seed_from_api.py --input data/raw/ --output seed/generated/

Outputs:
    seed/generated/SeedSpecBaseline.lua     — regenerated from API spec data
    seed/generated/SeedPvpTalentCatalog.lua — full PvP talent list by spec
"""

import os
import sys
import json
import argparse

# Spec IDs that are primarily melee DPS in PvP context.
# Used to override the generic API "DAMAGE" role type.
MELEE_SPEC_IDS = {
    71, 72, 73,       # Warrior (Arms, Fury, Protection)
    65, 70,           # Paladin (Protection, Retribution)
    250, 251, 252,    # Death Knight (Blood, Frost, Unholy)
    577, 581,         # Demon Hunter (Havoc, Vengeance)
    103, 104, 105,    # Druid (Feral, Guardian — Balance/Resto handled by API role)
    253, 255,         # Hunter (Beast Mastery, Survival)
    259, 260, 261,    # Rogue (Assassination, Outlaw, Subtlety)
    263,              # Shaman (Enhancement)
    268, 269,         # Monk (Brewmaster, Windwalker)
    72,               # Warrior Fury (duplicate safe — sets are deduped)
}


def spec_role(spec_id: int, api_role_type: str) -> str:
    if api_role_type == "TANK":   return "tank"
    if api_role_type == "HEALER": return "healer"
    if spec_id in MELEE_SPEC_IDS: return "melee"
    return "ranged"


def generate_spec_archetypes(specs: dict, classes: dict, output_path: str) -> None:
    lines = [
        "local _, ns = ...",
        "ns.GeneratedSeedData = ns.GeneratedSeedData or {}",
        "",
        "-- Auto-generated by scripts/generate_seed_from_api.py",
        "-- Source: Battle.net Playable Specialization API",
        "-- DO NOT EDIT MANUALLY — re-run the script to regenerate.",
        "",
        "ns.GeneratedSeedData.specBaseline = {",
    ]

    for spec_id_str, spec in sorted(specs.items(), key=lambda kv: int(kv[0])):
        spec_id    = int(spec_id_str)
        name       = spec.get("name", {}).get("en_US", "Unknown")
        api_role   = spec.get("role", {}).get("type", "DAMAGE")
        class_id   = spec.get("playable_class", {}).get("id", 0)
        class_data = classes.get(str(class_id), {})
        class_name = class_data.get("name", {}).get("en_US", "Unknown")
        role       = spec_role(spec_id, api_role)

        lines.append(
            f"    [{spec_id:6}] = {{"
            f" specId = {spec_id:6},"
            f" name = {json.dumps(name):<40},"
            f" class = {json.dumps(class_name):<22},"
            f" classId = {class_id:3},"
            f" role = {json.dumps(role):<12} }},"
        )

    lines += ["}", ""]
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  Written: {output_path}")


def generate_pvp_talent_catalog(pvp_talents: dict, output_path: str) -> None:
    lines = [
        "local _, ns = ...",
        "ns.GeneratedSeedData = ns.GeneratedSeedData or {}",
        "",
        "-- Auto-generated by scripts/generate_seed_from_api.py",
        "-- Source: Battle.net PvP Talent API",
        "-- DO NOT EDIT MANUALLY — re-run the script to regenerate.",
        "",
        "ns.GeneratedSeedData.pvpTalentCatalog = {",
    ]

    for talent_id_str, talent in sorted(pvp_talents.items(), key=lambda kv: int(kv[0])):
        talent_id = int(talent_id_str)
        name      = talent.get("name", {}).get("en_US", "Unknown")
        spec_id   = talent.get("playable_specialization", {}).get("id", 0)
        spell_id  = talent.get("spell", {}).get("id", 0)

        lines.append(
            f"    [{talent_id:6}] = {{"
            f" name = {json.dumps(name):<45},"
            f" specId = {spec_id:6},"
            f" spellId = {spell_id:8} }},"
        )

    lines += ["}", ""]
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  Written: {output_path}")


def load_json(path: str) -> dict:
    if not os.path.exists(path):
        print(f"ERROR: Input file not found: {path}", file=sys.stderr)
        print("Run fetch_blizzard_data.py first to generate raw API data.", file=sys.stderr)
        sys.exit(1)
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Lua seed files from fetched Battle.net API JSON"
    )
    parser.add_argument("--input",  default="data/raw/")
    parser.add_argument("--output", default="seed/generated/")
    args = parser.parse_args()

    os.makedirs(args.output, exist_ok=True)

    specs       = load_json(os.path.join(args.input, "specs.json"))
    classes     = load_json(os.path.join(args.input, "classes.json"))
    pvp_talents = load_json(os.path.join(args.input, "pvp_talents.json"))

    print("Generating SeedSpecBaseline.lua ...")
    generate_spec_archetypes(
        specs, classes,
        os.path.join(args.output, "SeedSpecBaseline.lua")
    )

    print("Generating SeedPvpTalentCatalog.lua ...")
    generate_pvp_talent_catalog(
        pvp_talents,
        os.path.join(args.output, "SeedPvpTalentCatalog.lua")
    )

    print("Done.")


if __name__ == "__main__":
    main()
