#!/usr/bin/env python3
"""
generate_seed_lua.py
====================
Reads curated JSON files from seed/raw/ and regenerates static Lua seed files.

Run after fetch scripts, or standalone to regenerate all Lua seed files from
their JSON sources without any API calls:

    python scripts/generate_seed_lua.py

Generates:
  seed/generated/SeedDummyCatalog.lua      <- seed/raw/dummy_catalog_overrides.json
  seed/generated/SeedSpecArchetypes.lua    <- seed/raw/spec_archetypes.json
  seed/generated/SeedSpellIntelligence.lua <- seed/raw/spell_intelligence_overrides.json
  seed/generated/SeedSpecMeta.lua          <- seed/raw/bnet_spec_meta.json    (if present)
  seed/generated/SeedPvpTalents.lua        <- seed/raw/bnet_pvp_talents.json  (if present)
"""

from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
ADDON_ROOT  = SCRIPT_DIR.parent
RAW_DIR     = ADDON_ROOT / "seed" / "raw"
SEED_DIR    = ADDON_ROOT / "seed" / "generated"
SEED_DIR.mkdir(parents=True, exist_ok=True)

TS = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

HEADER = """\
-- AUTO-GENERATED by scripts/generate_seed_lua.py
-- Generated: {ts}
-- Do NOT edit manually — edit the JSON source in seed/raw/ and re-run the script.

local _, ns = ...
ns.GeneratedSeedData = ns.GeneratedSeedData or {{}}
"""


# ---------------------------------------------------------------------------
# Lua value serializer
# ---------------------------------------------------------------------------

def _esc(s: str) -> str:
    """Escape a string for Lua double-quoted string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\r\n", " ").replace("\n", " ").replace("\r", " ") + '"'


def _lua_val(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return f"{v:.6g}"
    if isinstance(v, str):
        return _esc(v)
    if isinstance(v, list):
        if not v:
            return "{}"
        return "{ " + ", ".join(_lua_val(i) for i in v) + " }"
    if v is None:
        return "nil"
    return str(v)


def _inline_fields(fields: dict, skip: set[str] | None = None) -> str:
    """Serialize a flat dict as Lua inline table fields (no surrounding braces)."""
    skip = skip or set()
    parts = []
    for k, v in fields.items():
        if k in skip or k.startswith("_"):
            continue
        parts.append(f"{k} = {_lua_val(v)}")
    return ", ".join(parts)


# ---------------------------------------------------------------------------
# SeedDummyCatalog.lua
# ---------------------------------------------------------------------------
BOOL_FLAGS_DUMMY = {
    "isPvPUseful", "isRaidDummy", "isDungeonDummy", "isTrainingGrounds",
}

DUMMY_FIELD_ORDER = [
    "creatureID", "displayName", "normalizedName", "family",
    "benchmarkGroup", "isPvPUseful", "isRaidDummy", "isDungeonDummy", "isTrainingGrounds",
]


def write_dummy_catalog(ts: str) -> None:
    src = RAW_DIR / "dummy_catalog_overrides.json"
    if not src.exists():
        print(f"[skip] {src} not found")
        return

    data = json.loads(src.read_text(encoding="utf-8"))
    dummies = data.get("dummies", [])

    out = SEED_DIR / "SeedDummyCatalog.lua"
    lines = [HEADER.format(ts=ts)]
    lines.append("ns.GeneratedSeedData.dummyCatalog = {")

    for d in sorted(dummies, key=lambda x: x["creatureID"]):
        cid = d["creatureID"]
        lines.append(f"    [{cid}] = {{")
        for field in DUMMY_FIELD_ORDER:
            if field not in d:
                continue
            lines.append(f"        {field} = {_lua_val(d[field])},")
        lines.append("    },")

    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[ok] Wrote {out}  ({len(dummies)} dummies)")


# ---------------------------------------------------------------------------
# SeedSpecArchetypes.lua
# ---------------------------------------------------------------------------
ARCHETYPE_FIELD_ORDER = [
    "classFile", "specName", "role", "rangeBucket", "archetype", "threatTags",
]


def write_spec_archetypes(ts: str) -> None:
    src = RAW_DIR / "spec_archetypes.json"
    if not src.exists():
        print(f"[skip] {src} not found")
        return

    data = json.loads(src.read_text(encoding="utf-8"))
    specs = data.get("specs", [])

    out = SEED_DIR / "SeedSpecArchetypes.lua"
    lines = [HEADER.format(ts=ts)]
    lines.append("ns.GeneratedSeedData.specArchetypes = {")

    for s in sorted(specs, key=lambda x: x["specId"]):
        spec_id = s["specId"]
        # Build the inline table preserving field order
        parts = []
        for field in ARCHETYPE_FIELD_ORDER:
            if field not in s:
                continue
            parts.append(f"{field} = {_lua_val(s[field])}")
        lines.append(f"    [{spec_id}] = {{ {', '.join(parts)} }},")

    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[ok] Wrote {out}  ({len(specs)} specs)")


# ---------------------------------------------------------------------------
# SeedSpellIntelligence.lua
# ---------------------------------------------------------------------------

# Section comments to inject when a _section marker is encountered
SECTION_TITLES = {
    "TRINKET / GENERIC BREAK-CC":     "TRINKET / GENERIC BREAK-CC",
    "MAJOR OFFENSIVE CDs - Mage":     "MAJOR OFFENSIVE CDs",
    "MAJOR OFFENSIVE CDs - Paladin":  None,
    "MAJOR OFFENSIVE CDs - Warrior":  None,
    "MAJOR OFFENSIVE CDs - Hunter":   None,
    "MAJOR OFFENSIVE CDs - Rogue":    None,
    "MAJOR OFFENSIVE CDs - Priest":   None,
    "MAJOR OFFENSIVE CDs - Warlock":  None,
    "MAJOR OFFENSIVE CDs - Druid":    None,
    "MAJOR OFFENSIVE CDs - Shaman":   None,
    "MAJOR OFFENSIVE CDs - Death Knight": None,
    "MAJOR OFFENSIVE CDs - Demon Hunter": None,
    "MAJOR OFFENSIVE CDs - Monk":     None,
    "MAJOR OFFENSIVE CDs - Evoker":   None,
    "MAJOR DEFENSIVE CDs - Mage":     "MAJOR DEFENSIVE CDs",
    "MAJOR DEFENSIVE CDs - Paladin":  None,
    "MAJOR DEFENSIVE CDs - Warrior":  None,
    "MAJOR DEFENSIVE CDs - Rogue":    None,
    "MAJOR DEFENSIVE CDs - Hunter":   None,
    "MAJOR DEFENSIVE CDs - Priest":   None,
    "MAJOR DEFENSIVE CDs - Druid":    None,
    "MAJOR DEFENSIVE CDs - Shaman":   None,
    "MAJOR DEFENSIVE CDs - Warlock":  None,
    "MAJOR DEFENSIVE CDs - Death Knight": None,
    "MAJOR DEFENSIVE CDs - Demon Hunter": None,
    "MAJOR DEFENSIVE CDs - Monk":     None,
    "MAJOR DEFENSIVE CDs - Evoker":   None,
    "INTERRUPTS":                     "INTERRUPTS",
    "CROWD CONTROL - Stuns":          "CROWD CONTROL",
    "CROWD CONTROL - Roots":          None,
    "CROWD CONTROL - Fears":          None,
    "CROWD CONTROL - Incapacitates":  None,
    "CROWD CONTROL - Disorientations": None,
    "CROWD CONTROL - Horror / Sleep": None,
    "MOBILITY":                       "MOBILITY",
    "HEALING / RECOVERY":             "HEALING / RECOVERY",
    "ADDITIONAL OFFENSIVE UTILITY":   "ADDITIONAL OFFENSIVE UTILITY",
}

# Sub-comments per section for class groupings
SUBSECTION_LABELS: dict[str, str] = {
    "MAJOR OFFENSIVE CDs - Mage":     "Mage",
    "MAJOR OFFENSIVE CDs - Paladin":  "Paladin",
    "MAJOR OFFENSIVE CDs - Warrior":  "Warrior",
    "MAJOR OFFENSIVE CDs - Hunter":   "Hunter",
    "MAJOR OFFENSIVE CDs - Rogue":    "Rogue",
    "MAJOR OFFENSIVE CDs - Priest":   "Priest",
    "MAJOR OFFENSIVE CDs - Warlock":  "Warlock",
    "MAJOR OFFENSIVE CDs - Druid":    "Druid",
    "MAJOR OFFENSIVE CDs - Shaman":   "Shaman",
    "MAJOR OFFENSIVE CDs - Death Knight": "Death Knight",
    "MAJOR OFFENSIVE CDs - Demon Hunter": "Demon Hunter",
    "MAJOR OFFENSIVE CDs - Monk":     "Monk",
    "MAJOR OFFENSIVE CDs - Evoker":   "Evoker",
    "MAJOR DEFENSIVE CDs - Mage":     "Mage",
    "MAJOR DEFENSIVE CDs - Paladin":  "Paladin",
    "MAJOR DEFENSIVE CDs - Warrior":  "Warrior",
    "MAJOR DEFENSIVE CDs - Rogue":    "Rogue",
    "MAJOR DEFENSIVE CDs - Hunter":   "Hunter",
    "MAJOR DEFENSIVE CDs - Priest":   "Priest",
    "MAJOR DEFENSIVE CDs - Druid":    "Druid",
    "MAJOR DEFENSIVE CDs - Shaman":   "Shaman",
    "MAJOR DEFENSIVE CDs - Warlock":  "Warlock",
    "MAJOR DEFENSIVE CDs - Death Knight": "Death Knight",
    "MAJOR DEFENSIVE CDs - Demon Hunter": "Demon Hunter",
    "MAJOR DEFENSIVE CDs - Monk":     "Monk",
    "MAJOR DEFENSIVE CDs - Evoker":   "Evoker",
    "CROWD CONTROL - Stuns":          "Stuns",
    "CROWD CONTROL - Roots":          "Roots",
    "CROWD CONTROL - Fears":          "Fears",
    "CROWD CONTROL - Incapacitates":  "Incapacitates / Soft CC",
    "CROWD CONTROL - Disorientations": "Disorientations",
    "CROWD CONTROL - Horror / Sleep": "Horror / Sleep",
}

# Preferred field ordering for spell intelligence entries
SPELL_FIELD_ORDER = [
    "category", "isMajorOffensive", "isMajorDefensive", "isImmunity",
    "isTrinketLike", "isPvPTrinket", "isBurstEnabler", "breaksCC",
    "isRecoveryTool", "isInterrupt", "interruptFamily",
    "isCrowdControlStarter", "ccFamily", "isMobility",
    "notesTag", "cooldownSeconds",
]


def _spell_inline(entry: dict) -> str:
    parts = []
    for field in SPELL_FIELD_ORDER:
        if field not in entry:
            continue
        parts.append(f"{field} = {_lua_val(entry[field])}")
    # any extra fields not in the preferred order
    for field, val in entry.items():
        if field in SPELL_FIELD_ORDER or field.startswith("_") or field == "spellID":
            continue
        parts.append(f"{field} = {_lua_val(val)}")
    return "{ " + ", ".join(parts) + " }"


def write_spell_intelligence(ts: str) -> None:
    src = RAW_DIR / "spell_intelligence_overrides.json"
    if not src.exists():
        print(f"[skip] {src} not found")
        return

    data = json.loads(src.read_text(encoding="utf-8"))
    raw_spells = data.get("spells", [])

    out = SEED_DIR / "SeedSpellIntelligence.lua"
    lines = [HEADER.format(ts=ts)]
    lines.append("ns.GeneratedSeedData.spellIntelligence = {")
    lines.append("")

    spell_count = 0
    current_top_section: str | None = None
    current_sub_section: str | None = None

    for entry in raw_spells:
        # Section marker
        if "_section" in entry:
            sec = entry["_section"]
            top_title = SECTION_TITLES.get(sec)
            sub_label  = SUBSECTION_LABELS.get(sec)

            if top_title and top_title != current_top_section:
                # New top-level section header
                current_top_section = top_title
                current_sub_section = None
                sep = "=" * 57
                lines.append(f"    -- {sep}")
                lines.append(f"    -- {top_title}")
                lines.append(f"    -- {sep}")

            if sub_label and sub_label != current_sub_section:
                current_sub_section = sub_label
                lines.append(f"")
                lines.append(f"    -- {sub_label}")

            continue

        spell_id = entry.get("spellID")
        if spell_id is None:
            continue

        spell_count += 1
        inline = _spell_inline(entry)
        # Pad the spell ID column for alignment (up to 6 digits)
        id_str = f"[{spell_id}]"
        lines.append(f"    {id_str:<8} = {inline},")

    lines.append("")
    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[ok] Wrote {out}  ({spell_count} spells)")


# ---------------------------------------------------------------------------
# SeedSpecMeta.lua  (from cached bnet_spec_meta.json)
# ---------------------------------------------------------------------------
SPEC_META_FIELD_ORDER = [
    "specId", "specName", "className", "classId", "classFile", "role", "iconFileDataId",
]


def write_spec_meta_from_cache(ts: str) -> None:
    src = RAW_DIR / "bnet_spec_meta.json"
    if not src.exists():
        print(f"[skip] {src} not found — skipping SeedSpecMeta.lua (run fetch_bnet_seed.py first)")
        return

    raw = json.loads(src.read_text(encoding="utf-8"))
    # Keys may be strings (from JSON) — normalise to int
    spec_meta: dict[int, dict] = {int(k): v for k, v in raw.items()}

    out = SEED_DIR / "SeedSpecMeta.lua"
    lines = [HEADER.format(ts=ts)]
    lines.append("--- Official spec metadata sourced from the Blizzard Game Data API.")
    lines.append("--- @field specId         number")
    lines.append("--- @field specName       string")
    lines.append("--- @field className      string")
    lines.append("--- @field classId        number")
    lines.append("--- @field classFile      string  e.g. DEATHKNIGHT, DRUID …")
    lines.append("--- @field role           string  DAMAGE | HEALER | TANK")
    lines.append("--- @field iconFileDataId number|nil  WoW internal texture ID")
    lines.append("ns.GeneratedSeedData.specMeta = {")

    for spec_id in sorted(spec_meta.keys()):
        m = spec_meta[spec_id]
        icon = str(m["iconFileDataId"]) if m.get("iconFileDataId") else "nil"
        lines.append(f"    [{spec_id}] = {{")
        lines.append(f"        specId        = {spec_id},")
        lines.append(f"        specName      = {_esc(str(m.get('specName', '')))},")
        lines.append(f"        className     = {_esc(str(m.get('className', '')))},")
        lines.append(f"        classId       = {m.get('classId', 0)},")
        lines.append(f"        classFile     = {_esc(str(m.get('classFile', '')))},")
        lines.append(f"        role          = {_esc(str(m.get('role', 'DAMAGE')))},")
        lines.append(f"        iconFileDataId = {icon},")
        lines.append("    },")

    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[ok] Wrote {out}  ({len(spec_meta)} specs)")


# ---------------------------------------------------------------------------
# SeedPvpTalents.lua  (from cached bnet_pvp_talents.json)
# ---------------------------------------------------------------------------

def write_pvp_talents_from_cache(ts: str) -> None:
    src = RAW_DIR / "bnet_pvp_talents.json"
    if not src.exists():
        print(f"[skip] {src} not found — skipping SeedPvpTalents.lua (run fetch_bnet_seed.py first)")
        return

    raw = json.loads(src.read_text(encoding="utf-8"))
    by_spec: dict[int, list[dict]] = {int(k): v for k, v in raw.items()}

    # Load spec meta for class name comments (optional)
    spec_meta: dict[int, dict] = {}
    meta_src = RAW_DIR / "bnet_spec_meta.json"
    if meta_src.exists():
        spec_meta = {int(k): v for k, v in json.loads(meta_src.read_text()).items()}

    out = SEED_DIR / "SeedPvpTalents.lua"
    lines = [HEADER.format(ts=ts)]
    lines.append("--- PvP talents per spec, sourced from the Blizzard Game Data API.")
    lines.append("--- Each entry: { talentId, spellId, name, description, castTime, slots }.")
    lines.append("--- spellId can be used with C_Spell.GetSpellInfo(spellId) for icon lookup.")
    lines.append("--- slots: compatible PvP talent slot numbers (usually 1-4).")
    lines.append("ns.GeneratedSeedData.pvpTalents = {")

    total_talents = 0
    for spec_id in sorted(by_spec.keys()):
        talents = by_spec[spec_id]
        meta    = spec_meta.get(spec_id, {})
        comment = f"{meta.get('specName', '?')} {meta.get('className', '?')}"
        lines.append(f"    [{spec_id}] = {{  -- {comment}")

        for t in talents:
            spell_id  = t.get("spellId") or "nil"
            talent_id = t.get("talentId") or "nil"
            name      = _esc(t.get("name", ""))
            desc      = _esc(t.get("description", ""))
            cast_time = _esc(t.get("castTime", ""))
            slots_raw = t.get("compatibleSlots") or t.get("slots") or []
            slots_str = "{ " + ", ".join(str(s) for s in slots_raw) + " }" if slots_raw else "{}"
            lines.append(f"        {{ talentId = {talent_id}, spellId = {spell_id}, name = {name},")
            lines.append(f"          description = {desc},")
            lines.append(f"          castTime = {cast_time}, slots = {slots_str} }},")
            total_talents += 1

        lines.append("    },")

    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[ok] Wrote {out}  ({len(by_spec)} specs, {total_talents} talents)")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    print("=== CombatAnalytics seed Lua generator ===")
    print(f"Source : {RAW_DIR}")
    print(f"Output : {SEED_DIR}")
    print()

    write_dummy_catalog(TS)
    write_spec_archetypes(TS)
    write_spell_intelligence(TS)
    write_spec_meta_from_cache(TS)
    write_pvp_talents_from_cache(TS)

    print()
    print("Done.")


if __name__ == "__main__":
    main()
